### PR TITLE
V7 compatibilty changes, and new features

### PR DESCRIPTION
**Pull request by pburkholder**
## Changes proposed in this pull request:
- Updated hooks and tests for v7
- Using --unstaged will be much faster
- Add version pinning

## security considerations

None

### CODE REVIEW

**Comment by pburkholder** [comment]
@bengerman13 there's some ugliness around upgrading to 7.2.1 after our forced downgrade to 6.2.0, but this seems to work now more clean with 7.2.1 and uses the `--unstaged` switch so it should be much faster. Let me know.

**Comment by bengerman13** [comment]
@pburkholder I checked this out locally, did `make && make install` and now it seems to not work at all:
image

Did I install it wrong or ...?

**Comment by pburkholder** [comment]
Ah, I put the version check in `make audit` but not in the `make` default path, which is the same as `make install`.

Try `make upgrade`.  If that works I'll do another commit to fix the `install` stanza. 

Sorry you're hitting this. The `brew` team removed the `switch` feature in December, so it's harder now to upgrade cleanly after we did a forced downgrade to gitleaks 6.2.0.

**Comment by bengerman13** [comment]
That seems to be working, and way faster as promised!

**Pull request merged**
